<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Assets\WW2\Core\**\*.cs" />
    <Compile Include="..\..\Assets\WW2\Runtime\**\*.cs" />
    <Compile Include="..\..\Assets\WW2\Editor\**\*.cs" />
    <Reference Include="UnityEngine">
      <HintPath>$(UnityManagedPath)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEditor">
      <HintPath>$(UnityManagedPath)\UnityEditor.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>

